version: '3'

networks:
  backend:
      driver: bridge
      ipam:
          driver: default
          config:
              - subnet: 172.10.2.0/23

services:
  postgres:
    image: "postgres:alpine"
    container_name: postgres
    ports:
      - '0.0.0.0:5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    environment:
     POSTGRES_PASSWORD: password
     POSTGRES_DB: ark_testnet
     POSTGRES_USER: ark
    networks:
      backend:
        ipv4_address: 172.10.2.2

  node:
    build: .
    container_name: node
    tty: true
    privileged: true
    working_dir: /core/packages/core
    volumes:
      - core:/core
      - ./config/core1:/core_config
    environment:
      CORE_DB_HOST: postgres
      CORE_PATH_CONFIG: /core_config
    ports:
      - "4000:4000"
      - "0.0.0.0:4013:4003"
    networks:
      backend:
          ipv4_address: 172.10.3.2
    command: "/bin/sh -c 'yarn ark core:run --env=test --network=testnet'"

volumes:
  postgres:
  core:
    driver_opts:
      type: none
      device: /home/$USER/core
      o: bind
